### ISSUE TITLE
Invalid capacities 1.20.1  2.1.0 beta 3

### ISSUE THREAD

**Issue by border999** [Harveykang/AsyncParticles#96]
[crash-2025-07-04_16.10.06-client.txt](https://github.com/user-attachments/files/21066159/crash-2025-07-04_16.10.06-client.txt)
Attempted to upload to pastebin and gist.github but neither would take the entire log

**Comment by Harveykang** [comment]
Could you let me know how to reproduce the issue?
For example, did you update the mod version or manually edit the config files before the crash?

**Comment by border999** [comment]
updated the mod. I believe I was on beta 1 or alpha 6 previously. I would try it from the 2.0.1 stable release as a control.

**Comment by Harveykang** [comment]
there was an issue migrating from the old config(v1.x), restarting should fix it, but this will set the particle count to 1024. so don't forget to reset settings in-game.
i'll fix this in the next version

**Comment by border999** [comment]
noted. I will leave it to you to close this issue when the fix is published.

**Comment by border999** [comment]
Loaded up AsyncParticles-2.1.0-beta.3+1.20.1, crashed, tried to load game again as was recommened above. Still crashed.
Deleted the config files for AsyncParticles, still crashed.
Dropping you the last crash because they appear to all be identical at first glance.
[crash-2025-07-06_16.11.03-client.txt](https://github.com/user-attachments/files/21091368/crash-2025-07-06_16.11.03-client.txt)

**Comment by Harveykang** [comment]
Not quite sure what's happening here. i test several cases and it doesn't crash on my end.
Could you send me the `config/asyncparticles.properties` and `config/asyncparticles/asyncparticles.json`?

**Comment by border999** [comment]
https://gist.github.com/border999/a4ff279bca0b208acbdb9df8922cdb5b
mixins are the only thing being created before the crash so no other config files for you unless I revert to a known working version first then update. Dropping latest log and debug log. together this should all paint you a pretty complete picture. I always knew that running such a massive petridish of mods would have me catching all the edgecases of crashes. It helps devs because If I don't have issues, that's a veritable army of mods that work together.
[debug.log](https://github.com/user-attachments/files/21093952/debug.log)
[latest.log](https://github.com/user-attachments/files/21093946/latest.log)

**Comment by Harveykang** [comment]
It seems something is causing the ParticleEngine to initialize before the config is loaded. Not quite sure what is that yet, but there will be a mitigation in the next version.

**Comment by Harveykang** [comment]
could you try this build and see if it still crashes? Thanks a lot!

[AsyncParticles-2.1.0-beta.4-SNAPSHOT.15febf66+1.20.1.jar.zip](https://github.com/user-attachments/files/21094477/AsyncParticles-2.1.0-beta.4-SNAPSHOT.15febf66%2B1.20.1.jar.zip)

(please remove the `.zip` extension manually as can't upload a jar file here)

**Comment by border999** [comment]
[crash-2025-07-07_16.06.20-fml.txt](https://github.com/user-attachments/files/21109538/crash-2025-07-07_16.06.20-fml.txt)
new crash. looks to be referencing the citadel mod. but the config looks to have actually generated one more file.
[asyncparticles.json](https://github.com/user-attachments/files/21109546/asyncparticles.json)
still is not generating  config/asyncparticles.properties 
[debug.log](https://github.com/user-attachments/files/21109579/debug.log)
[latest.log](https://github.com/user-attachments/files/21109580/latest.log)

**Comment by Harveykang** [comment]
this might not be related to AsyncParticles.
the `config/asyncparticles.properties` is the old config of v1.x, it's no longer used except for config migration.

**Comment by border999** [comment]
diagnostic in progress.

**Comment by border999** [comment]
downgraded citadel from 2.6.2 to 2.6.1. was able to log to main menu. However, these are all that generated in the config for async.
[asyncparticles.json](https://github.com/user-attachments/files/21110009/asyncparticles.json)
[asyncparticles-mixin.properties.txt](https://github.com/user-attachments/files/21110010/asyncparticles-mixin.properties.txt)

**Comment by Harveykang** [comment]
> [asyncparticles.json](https://github.com/user-attachments/files/21110009/asyncparticles.json)
 [asyncparticles-mixin.properties.txt](https://github.com/user-attachments/files/21110010/asyncparticles-mixin.properties.txt)

yeah, it seems working as intended.

**Comment by border999** [comment]
I will call this issue closed then for the time being and continue to use the shapshot you linked.
